const SWITCH_TO_PREV_MONTH = "SWITCH_TO_PREV_MONTH";
const SWITCH_TO_NEXT_MONTH = "SWITCH_TO_NEXT_MONTH";
const CHANGE_SELECTED_DATE = "CHANGE_SELECTED_DATE";
const TOGGLE_IS_EDITING_DATE = "TOGGLE_IS_EDITING_DATE";
const CHANGE_SELECTED_MONTH = "CHANGE_SELECTED_MONTH";

export { SWITCH_TO_PREV_MONTH, SWITCH_TO_NEXT_MONTH, CHANGE_SELECTED_DATE, TOGGLE_IS_EDITING_DATE, CHANGE_SELECTED_MONTH };