const SELECT_VISIBLE_MONTH = "SELECT_VISIBLE_MONTH";
const SAVE_CLOSE_CALENDAR = "SAVE_CLOSE_CALENDAR";
const CANCEL_CLOSE_CALENDAR = "CANCEL_CLOSE_CALENDAR";
const SWITCH_TO_NEXT_MONTH = "SWITCH_TO_NEXT_MONTH";

export { SELECT_VISIBLE_MONTH, SAVE_CLOSE_CALENDAR, SWITCH_TO_NEXT_MONTH, CANCEL_CLOSE_CALENDAR };