const CHANGE_COMPLETED = "CHANGE_COMPLETED";
const CHANGE_IMPORTANT = "CHANGE_IMPORTANT";
const CHANGE_TITLE = "CHANGE_TITLE";
const CHANGE_NOTE = "CHANGE_NOTE";
const CHOOSE_DEADLINE = "CHOOSE_DEADLINE";
const DELETE_DEADLINE = "DELETE_DEADLINE";
const DELETE_TODO = "DELETE_TODO";

export { 
    CHANGE_COMPLETED, 
    CHANGE_IMPORTANT, 
    CHANGE_TITLE, 
    CHANGE_NOTE, 
    CHOOSE_DEADLINE, 
    DELETE_DEADLINE, 
    DELETE_TODO };
