const CHANGE_ACTIVE_TODO_ID = "CHANGE_ACTIVE_TODO_ID";
const TOOGLE_DELETING_TODO = "TOOGLE_DELETING_TODO";
const TOGGLE_TODO_EDIT_PANEL = "TOGGLE_TODO_EDIT_PANEL";
const TOGGLE_CHOOSE_DEADLINE_MODAL = "TOGGLE_CHOOSE_DEADLINE_MODAL";
const OPEN_CALENDAR = "TOGGLE_CALENDAR";

export { 
    CHANGE_ACTIVE_TODO_ID,
    TOOGLE_DELETING_TODO,
    TOGGLE_TODO_EDIT_PANEL, 
    TOGGLE_CHOOSE_DEADLINE_MODAL, 
    OPEN_CALENDAR };