const TOGGLE_RENAMING_LIST = "SET_RENAMING_LIST";
const TOOGLE_DELETING_LIST = "TOOGLE_DELETING_LIST";
const TOOGLE_CREATING_LIST = "TOOGLE_CREATING_LIST";
const TOOGLE_CREATING_TODO = "TOOGLE_CREATING_TODO";
const SWITCH_ACTIVE_TODOLIST_ID = "SWITCH_TODOLIST";
const SWITCH_VISIBLE_COMPLETED = "SWITCH_VISIBLE_COMPLETED";
const SWITCH_VISIBLE_IMPORTANT = "SWITCH_VISIBLE_IMPORTANT";
const SEARCH = "SEARCH";

export { 
    SWITCH_ACTIVE_TODOLIST_ID, 
    TOOGLE_CREATING_TODO, 
    TOOGLE_CREATING_LIST, 
    TOOGLE_DELETING_LIST, 
    SWITCH_VISIBLE_COMPLETED, 
    SWITCH_VISIBLE_IMPORTANT, 
    SEARCH, 
    TOGGLE_RENAMING_LIST };
